// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"; // 自动加载 .env
import { config as dotenvConfig } from "dotenv";

// 额外加载 .env.local（Next.js 约定，优先级更高）
dotenvConfig({ path: ".env.local", override: false });

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
